<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190601120851 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE quotation ADD project_client VARCHAR(255) DEFAULT NULL, ADD project_contact VARCHAR(255) DEFAULT NULL, ADD project_address VARCHAR(255) DEFAULT NULL, ADD project_city VARCHAR(255) DEFAULT NULL, ADD project_postcode VARCHAR(255) DEFAULT NULL, CHANGE id id VARCHAR(255) NOT NULL, CHANGE unit_price1 unit_price1 VARCHAR(255) DEFAULT NULL, CHANGE quantity1 quantity1 VARCHAR(255) DEFAULT NULL, CHANGE unit_price2 unit_price2 VARCHAR(255) DEFAULT NULL, CHANGE quantity2 quantity2 VARCHAR(255) DEFAULT NULL, CHANGE unit_price3 unit_price3 VARCHAR(255) DEFAULT NULL, CHANGE quantity3 quantity3 VARCHAR(255) DEFAULT NULL, CHANGE unit_price4 unit_price4 VARCHAR(255) DEFAULT NULL, CHANGE quantity4 quantity4 VARCHAR(255) DEFAULT NULL, CHANGE unit_price5 unit_price5 VARCHAR(255) DEFAULT NULL, CHANGE quantity5 quantity5 VARCHAR(255) DEFAULT NULL, CHANGE unit_price6 unit_price6 VARCHAR(255) DEFAULT NULL, CHANGE quantity6 quantity6 VARCHAR(255) DEFAULT NULL, CHANGE unit_price7 unit_price7 VARCHAR(255) DEFAULT NULL, CHANGE quantity7 quantity7 VARCHAR(255) DEFAULT NULL, CHANGE unit_price8 unit_price8 VARCHAR(255) DEFAULT NULL, CHANGE quantity8 quantity8 VARCHAR(255) DEFAULT NULL, CHANGE unit_price9 unit_price9 VARCHAR(255) DEFAULT NULL, CHANGE quantity9 quantity9 VARCHAR(255) DEFAULT NULL, CHANGE unit_price10 unit_price10 VARCHAR(255) DEFAULT NULL, CHANGE quantity10 quantity10 VARCHAR(255) DEFAULT NULL, CHANGE unit_price11 unit_price11 VARCHAR(255) DEFAULT NULL, CHANGE quantity11 quantity11 VARCHAR(255) DEFAULT NULL, CHANGE unit_price12 unit_price12 VARCHAR(255) DEFAULT NULL, CHANGE quantity12 quantity12 VARCHAR(255) DEFAULT NULL, CHANGE unit_price13 unit_price13 VARCHAR(255) DEFAULT NULL, CHANGE quantity13 quantity13 VARCHAR(255) DEFAULT NULL, CHANGE unit_price14 unit_price14 VARCHAR(255) DEFAULT NULL, CHANGE quantity14 quantity14 VARCHAR(255) DEFAULT NULL, CHANGE unit_price15 unit_price15 VARCHAR(255) DEFAULT NULL, CHANGE quantity15 quantity15 VARCHAR(255) DEFAULT NULL, CHANGE project_id project_id VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at VARCHAR(255) DEFAULT NULL, CHANGE price_total price_total VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE bill CHANGE id id VARCHAR(255) NOT NULL, CHANGE quantity1 quantity1 VARCHAR(255) DEFAULT NULL, CHANGE unit_price1 unit_price1 VARCHAR(255) DEFAULT NULL, CHANGE quantity2 quantity2 VARCHAR(255) DEFAULT NULL, CHANGE unit_price2 unit_price2 VARCHAR(255) DEFAULT NULL, CHANGE quantity3 quantity3 VARCHAR(255) DEFAULT NULL, CHANGE unit_price3 unit_price3 VARCHAR(255) DEFAULT NULL, CHANGE quantity4 quantity4 VARCHAR(255) DEFAULT NULL, CHANGE unit_price4 unit_price4 VARCHAR(255) DEFAULT NULL, CHANGE project_id project_id VARCHAR(255) DEFAULT NULL, CHANGE quantity5 quantity5 VARCHAR(255) DEFAULT NULL, CHANGE unit_price5 unit_price5 VARCHAR(255) DEFAULT NULL, CHANGE quantity6 quantity6 VARCHAR(255) DEFAULT NULL, CHANGE quantity7 quantity7 VARCHAR(255) DEFAULT NULL, CHANGE unit_price7 unit_price7 VARCHAR(255) DEFAULT NULL, CHANGE quantity8 quantity8 VARCHAR(255) DEFAULT NULL, CHANGE unit_price8 unit_price8 VARCHAR(255) DEFAULT NULL, CHANGE quantity9 quantity9 VARCHAR(255) DEFAULT NULL, CHANGE unit_price9 unit_price9 VARCHAR(255) DEFAULT NULL, CHANGE quantity10 quantity10 VARCHAR(255) DEFAULT NULL, CHANGE unit_price10 unit_price10 VARCHAR(255) DEFAULT NULL, CHANGE quantity11 quantity11 VARCHAR(255) DEFAULT NULL, CHANGE unit_price11 unit_price11 VARCHAR(255) DEFAULT NULL, CHANGE quantity12 quantity12 VARCHAR(255) DEFAULT NULL, CHANGE unit_price12 unit_price12 VARCHAR(255) DEFAULT NULL, CHANGE quantity13 quantity13 VARCHAR(255) DEFAULT NULL, CHANGE unit_price13 unit_price13 VARCHAR(255) DEFAULT NULL, CHANGE quantity14 quantity14 VARCHAR(255) DEFAULT NULL, CHANGE unit_price14 unit_price14 VARCHAR(255) DEFAULT NULL, CHANGE quantity15 quantity15 VARCHAR(255) DEFAULT NULL, CHANGE unit_price15 unit_price15 VARCHAR(255) DEFAULT NULL, CHANGE payment_period payment_period VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE price_total price_total VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE bill CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE quantity1 quantity1 INT DEFAULT NULL, CHANGE unit_price1 unit_price1 INT DEFAULT NULL, CHANGE quantity2 quantity2 INT DEFAULT NULL, CHANGE unit_price2 unit_price2 INT DEFAULT NULL, CHANGE quantity3 quantity3 INT DEFAULT NULL, CHANGE unit_price3 unit_price3 INT DEFAULT NULL, CHANGE quantity4 quantity4 INT DEFAULT NULL, CHANGE unit_price4 unit_price4 INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE quantity5 quantity5 INT DEFAULT NULL, CHANGE unit_price5 unit_price5 INT DEFAULT NULL, CHANGE quantity6 quantity6 INT DEFAULT NULL, CHANGE quantity7 quantity7 INT DEFAULT NULL, CHANGE unit_price7 unit_price7 INT DEFAULT NULL, CHANGE quantity8 quantity8 INT DEFAULT NULL, CHANGE unit_price8 unit_price8 INT DEFAULT NULL, CHANGE quantity9 quantity9 INT DEFAULT NULL, CHANGE unit_price9 unit_price9 INT DEFAULT NULL, CHANGE quantity10 quantity10 INT DEFAULT NULL, CHANGE unit_price10 unit_price10 INT DEFAULT NULL, CHANGE quantity11 quantity11 INT DEFAULT NULL, CHANGE unit_price11 unit_price11 INT DEFAULT NULL, CHANGE quantity12 quantity12 INT DEFAULT NULL, CHANGE unit_price12 unit_price12 INT DEFAULT NULL, CHANGE quantity13 quantity13 INT DEFAULT NULL, CHANGE unit_price13 unit_price13 INT DEFAULT NULL, CHANGE quantity14 quantity14 INT DEFAULT NULL, CHANGE unit_price14 unit_price14 INT DEFAULT NULL, CHANGE quantity15 quantity15 INT DEFAULT NULL, CHANGE unit_price15 unit_price15 INT DEFAULT NULL, CHANGE payment_period payment_period INT DEFAULT NULL, CHANGE status status INT DEFAULT NULL, CHANGE price_total price_total INT DEFAULT NULL');
        $this->addSql('ALTER TABLE quotation DROP project_client, DROP project_contact, DROP project_address, DROP project_city, DROP project_postcode, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE unit_price1 unit_price1 INT DEFAULT NULL, CHANGE quantity1 quantity1 INT DEFAULT NULL, CHANGE unit_price2 unit_price2 INT DEFAULT NULL, CHANGE quantity2 quantity2 INT DEFAULT NULL, CHANGE unit_price3 unit_price3 INT DEFAULT NULL, CHANGE quantity3 quantity3 INT DEFAULT NULL, CHANGE unit_price4 unit_price4 INT DEFAULT NULL, CHANGE quantity4 quantity4 INT DEFAULT NULL, CHANGE unit_price5 unit_price5 INT DEFAULT NULL, CHANGE quantity5 quantity5 INT DEFAULT NULL, CHANGE unit_price6 unit_price6 INT DEFAULT NULL, CHANGE quantity6 quantity6 INT DEFAULT NULL, CHANGE unit_price7 unit_price7 INT DEFAULT NULL, CHANGE quantity7 quantity7 INT DEFAULT NULL, CHANGE unit_price8 unit_price8 INT DEFAULT NULL, CHANGE quantity8 quantity8 INT DEFAULT NULL, CHANGE unit_price9 unit_price9 INT DEFAULT NULL, CHANGE quantity9 quantity9 INT DEFAULT NULL, CHANGE unit_price10 unit_price10 INT DEFAULT NULL, CHANGE quantity10 quantity10 INT DEFAULT NULL, CHANGE unit_price11 unit_price11 INT DEFAULT NULL, CHANGE quantity11 quantity11 INT DEFAULT NULL, CHANGE unit_price12 unit_price12 INT DEFAULT NULL, CHANGE quantity12 quantity12 INT DEFAULT NULL, CHANGE unit_price13 unit_price13 INT DEFAULT NULL, CHANGE quantity13 quantity13 INT DEFAULT NULL, CHANGE unit_price14 unit_price14 INT DEFAULT NULL, CHANGE quantity14 quantity14 INT DEFAULT NULL, CHANGE unit_price15 unit_price15 INT DEFAULT NULL, CHANGE quantity15 quantity15 INT DEFAULT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE price_total price_total INT DEFAULT NULL');
    }
}
