knp_snappy:
    pdf:
        enabled:    true
        binary:     "/usr/local/bin/wkhtmltopdf"
        options:
           page-size: A4
           dpi: 300
           image-quality: 80
           user-style-sheet: "%kernel.root_dir%/../templates/quotation.css"

    image:
        enabled:    true
        binary:     "/usr/local/bin/wkhtmltoimage"
        options:    []
